Help center article for privacy settings
famedly/helpcenter pull request #38
Opened 2023-09-11 08:56 UTC by mErrenst

On Account Settings: 
![Bildschirmfoto vom 2023-09-11 10-51-38](https://github.com/famedly/helpcenter/assets/139118252/3eec1954-5fb8-47c7-9394-36ca6717ddf9)
![Bildschirmfoto vom 2023-09-11 10-52-12](https://github.com/famedly/helpcenter/assets/139118252/c93001e6-63fb-42dd-96b9-92807f4cd0e7)

Closes https://github.com/famedly/product-management/issues/1349

2023-09-12 16:25 UTC, rvanwaveren requested changes
Under Login line 17 change wording to not repeat können. e.g. strike the first repetition of können.
Line 36 - with users we do not really talk about the url of a matrix server. Geben Sie die Anmelde-URL ein, is sufficient.
Line 53-56 - In the preview, this was not properly translated (verification instead of Verifikation)
Datenschutz:
188 - Alle chat-Features aktivieren, kann man deaktivieren. Das macht irgendwie keinen Sinn. Da sollte dann stehen 'alle features' und dann der Slider für aktivieren und deaktivieren, aber nicht das aktivieren deaktivieren.

2023-09-14 13:22 UTC, nico-famedly requested changes

2023-09-14 13:22 UTC, nico-famedly commented on docs/help-center/using-famedly/login.mdx
> +    <li>Enter your matrix servers URL in the input field <b>Login URL</b>.</li>
```suggestion
    <li>Enter your login URL into the corresponding input field.</li>
```

2023-09-14 13:22 UTC, nico-famedly commented on i18n/de/docusaurus-plugin-content-docs/current/help-center/using-famedly/login.mdx
> +    <p class="hero__subtitle">Wie Sie sich bei Famedly Anmelden können und welche Einstellungen beim Anmeldeprozess gemacht werden können</p>
```suggestion
    <p class="hero__subtitle">Wie Sie sich bei Famedly anmelden und welche Einstellungen beim Anmeldeprozess gemacht werden können</p>
```

2023-09-14 13:26 UTC, nico-famedly approved these changes

2023-09-14 13:28 UTC, merged