Add instructions for copy and paste
famedly/helpcenter pull request #62
Opened 2023-11-29 15:34 UTC by nico-famedly

Also moves the drag and drop box to be desktop specific.

fixes https://github.com/famedly/app/issues/5407

2023-11-29 15:35 UTC, nico-famedly commented
Suggestions for how to word copy and paste are welcome!

2023-12-04 12:22 UTC, rvanwaveren requested changes

2023-12-04 12:22 UTC, rvanwaveren commented on i18n/de/docusaurus-plugin-content-docs/current/help-center/using-famedly/share-files.mdx
> +Kopierte dateien können auch direkt in den Chat eingefügt werden, entweder durch das Kontextmenü oder durch ein Tastenkürzel. Unter Firefox kann nur eine Datei gleichzeitig eingefügt werden.
Wenn ich nicht weiß was ein Kontextmenü sein sollte, dann der Nutzer auch nicht. Hier wäre eine Erklärung von dem, was man machen sollte, vielleicht besser, um das Wort zu umgehen.

2023-12-04 12:22 UTC, rvanwaveren commented on i18n/de/docusaurus-plugin-content-docs/current/help-center/using-famedly/share-files.mdx
> +Kopierte Bilder oder Videos können auch direkt in den Chat eingefügt werden, entweder durch das Kontextmenü oder durch ein Tastenkürzel. Unter Firefox kann nur eine Datei gleichzeitig eingefügt werde
Dito

2023-12-04 14:58 UTC, rvanwaveren approved these changes

2023-12-04 15:42 UTC, merged